LCLDemo/LCL.WebMvc/Controllers/LayoutController.cs
using LCL.Domain.Model;
using LCL.Domain.Services;
using System;
using System.Web.Mvc;

namespace LCL.WebMvc.Controllers
{
    [HandleError]
    public class LayoutController : CommonController
    {
        public ActionResult CategoriesPartial(string categoryID = null)
        {
            using (var proxy = this.Service<IProductService>())
            {
                var categories = proxy.GetCategories();
                if (string.IsNullOrEmpty(categoryID))
                    ViewBag.CategoryName = "";
                else
                {
                    var category = proxy.GetCategoryByID(new Guid(categoryID));
                    ViewBag.CategoryName = category.Name;
                }
                return PartialView(categories);
            }
        }
        public ActionResult _LoginPartial()
        {
            if (User.Identity.IsAuthenticated)
            {
                using (var proxy = this.Service<IOrderService>())
                {
                    ViewBag.ShoppingCartItems = proxy.GetShoppingCartItemCount(UserID);
                }
            }
            return PartialView();
        }
        public ActionResult FeaturedProductsPartial()
        {
            using (var proxy = this.Service<IProductService>())
            {
                var featuredProducts = proxy.GetFeaturedProducts(4);
                return PartialView(featuredProducts);
            }
        }
        public ActionResult ProductsPartial(string categoryID = null, bool? fromIndexPage = null, int pageNumber = 1)
        {
            using (var proxy = this.Service<IProductService>())
            {

                PagedResult<Product> productsWithPagination = null;
                if (string.IsNullOrEmpty(categoryID))
                    productsWithPagination = proxy.GetProductsWithPagination(pageNumber, 10);
                else
                    productsWithPagination = proxy.GetProductsForCategoryWithPagination(new Guid(categoryID), pageNumber, 10);

                if (fromIndexPage != null && !fromIndexPage.Value)
                {
                    if (string.IsNullOrEmpty(categoryID))
                    {
                        ViewBag.CategoryName = "所有商品";
                    }
                    else
                    {
                        var category = proxy.GetCategoryByID(new Guid(categoryID));
                        ViewBag.CategoryName = category.Name;
                    }
                }
                else
                {
                    ViewBag.CategoryName = null;
                }
                ViewBag.CategoryID = categoryID;
                ViewBag.FromIndexPage = fromIndexPage;
                if (fromIndexPage == null || fromIndexPage.Value)
                    ViewBag.Action = "Index";
                else
                    ViewBag.Action = "Category";
                if (productsWithPagination != null)
                {
                    ViewBag.IsFirstPage = productsWithPagination.PageNumber == 1;
                    ViewBag.IsLastPage = productsWithPagination.PageNumber == productsWithPagination.TotalPages;
                }
                return PartialView(productsWithPagination);
            }
        }
    }
}

LCLDemo/LCL.WebMvc/Controllers/ProductController.cs
using LCL.Domain.Model;
using LCL.Domain.Repositories;
using LCL.Domain.Services;
using System;
using System.Web.Mvc;

namespace LCL.WebMvc.Controllers
{
    public class ProductController : CommonController<Product>
    {
        public override ActionResult Index(int? currentPageNum, int? pageSize, FormCollection collection)
        {
            return base.Index(currentPageNum, pageSize, collection);
        }
        public ActionResult Category(string categoryID = null, int pageNumber = 1)
        {
            ViewData["CategoryID"] = categoryID;
            ViewData["FromIndexPage"] = false;
            return View();
        }
        public ActionResult ProductInfo(Guid id)
        {
            using (var proxy = this.Service<IProductService>())
            {
                var product = proxy.GetProductByID(id);
                return View(product);
            }
        }

    }
}

LCLDemo/LCL.WebMvc/Views/Product/Category.cshtml
@using LCL;
@{
    ViewBag.Title = "商品" + ViewBag.CategoryName;
}
<div class="container bs-docs-container">
    <div class="row">
        @{Html.RenderAction("FeaturedProductsPartial", "Layout");}
    </div>
    <br />
    <div class="row">
        <div class="col-md-9" role="main">
            @{Html.RenderAction("ProductsPartial", "Layout",
                  new { categoryID = ViewData["CategoryID"], fromIndexPage = ViewData["FromIndexPage"] });}

        </div>
        <div class="col-md-3" role="complementary">
            @{Html.RenderAction("CategoriesPartial", "Layout");}
        </div>
    </div>
</div>

LCLDemo/LCL.WebMvc/Views/Product/Index.cshtml
@using LCL;
@{
    ViewBag.Title = "商品" + ViewBag.CategoryName;
}
<div class="container bs-docs-container">
    <div class="row">
        @{Html.RenderAction("FeaturedProductsPartial", "Layout");}
    </div>
    <br />
    <div class="row">
        <div class="col-md-9" role="main">
            @{Html.RenderAction("ProductsPartial", "Layout");}
        </div>
        <div class="col-md-3" role="complementary">
            @{Html.RenderAction("CategoriesPartial", "Layout");}
        </div>
    </div>
</div>

LCLDemo/LCL.WebMvc/Views/Product/ProductInfo.cshtml
@model LCL.Domain.Model.Product

@{
    ViewBag.Title = Model.Name;
}

<div class="container bs-docs-container">
    <div class="row">
        @{Html.RenderAction("FeaturedProductsPartial", "Layout");}
    </div>
    <br />
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <table>
        <tr>
            <td>
                <img src="@Url.Content(string.Format("~/Images/Products/{0}",Model.ImageUrl))" alt="" width="175" height="144" border="0">
            </td>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UnitPrice)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UnitPrice)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsFeatured)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsFeatured)
                    </dd>

                </dl>

            </td>
        </tr>
    </table>

</div>